export const portfolioData = [
  {
    filter: "react",
    id: "dashboard",
    img: "dashboardReact",
    title: "React dashboard ",
    describtion: "",
    skills: ["React", "HTML/CSS"],
    code: "https://github.com/hyemin12/react-dashboard-app",
    site: "https://react-movie-app-1f5ff8.netlify.app/",
  },
  {
    filter: "react",
    id: "movie",
    img: "movieReact",
    title: "React 영화 검색사이트",
    describtion: "",
    skills: ["React", "HTML/CSS"],
    code: "https://github.com/hyemin12/react-movie-app",
    site: "https://react-movie-app-1f5ff8.netlify.app/",
  },
  {
    filter: "vanillaJS",
    id: "moment",
    img: "momentJS",
    title: "바닐라JS moment app",
    describtion: "",
    code: "https://github.com/hyemin12/vanillaJS-chrome-app",
    site: "https://hyemin12.github.io/vanillaJS-chrome-app/",
  },
  {
    filter: "ect",
    id: "ect",
    img: "challengeJS",
    title: "바닐라JS challenge",
    describtion: "",
    code: "https://github.com/hyemin12/vanillaJS-challenge/",
    site: "https://hyemin12.github.io/vanillaJS-challenge/",
  },
  {
    filter: "vanillaJS",
    id: "wordle",
    img: "wordleJS",
    title: "바닐라JS Wordle app",
    describtion: "",
    code: "https://github.com/hyemin12/vanillaJS-wordle-app",
    site: "https://hyemin12.github.io/vanillaJS-wordle-app/",
  },
  {
    filter: "vanillaJS",
    id: "paint",
    img: "paintJS",
    title: "바닐라JS 그림판 app",
    describtion: "",
    code: "https://github.com/hyemin12/vanillaJS-paint-app",
    site: "https://hyemin12.github.io/vanillaJS-paint-app/",
  },
  {
    filter: "vanillaJS",
    id: "starbucks",
    img: "starbucks",
    title: "HTML/CSS starbucks",
    describtion: "",
    code: "https://github.com/hyemin12/basic-starbucks-app",
    site: "https://starbucks-responsive-app-ee135b.netlify.app",
  },
  {
    filter: "react",
    id: "gomintalk",
    img: "gominTalk",
    title: "React gomin Talk",
    describtion: "",
    code: "https://github.com/hyemin12/gomin-talk-app",
    site: "https://wizardly-hermann-7fecb3.netlify.app/",
  },
  {
    filter: "ect",
    id: "overwatch",
    img: "overwatch",
    title: "HTML/CSS Overwatch",
    describtion: "",
    code: "https://github.com/hyemin12/display-flex-overwatch",
    site: "https://hyemin12.github.io/display-flex-overwatch/",
  },
  {
    filter: "jquery",
    id: "stranger",
    img: "stranger",
    title: "jQuery Fullpage 비밀의숲2",
    describtion: "",
    code: "https://github.com/hyemin12/web-design-portfolio/01Stranger2/",
    site: "https://hyemin12.github.io/web-design-portfolio/01Stranger2/",
  },
  {
    filter: "ect",
    id: "melon",
    img: "melon",
    title: "HTML/CSS 멜론",
    describtion: "",
    code: "https://github.com/hyemin12/web-design-portfolio/04Melon/",
    site: "https://hyemin12.github.io/web-design-portfolio/04Melon/",
  },
  {
    filter: "jquery",
    id: "nonstop",
    img: "nonstop",
    title: "jQeury Fullpage 프로모션",
    describtion: "",
    code: "https://github.com/hyemin12/web-design-portfolio/03OHMYGIRL/",
    site: "https://hyemin12.github.io/web-design-portfolio/03OHMYGIRL/index2.html#a5st",
  },
  {
    filter: "jquery",
    id: "2021portfolio",
    img: "2021portfolio",
    title: "jQeury Fullpage 2021 포트폴리오",
    describtion: "",
    code: "https://github.com/hyemin12/web-design-portfolio/05portfolio_fullpage/",
    site: "https://hyemin12.github.io/web-design-portfolio/05portfolio_fullpage/#a1st",
  },
];
